import javax.swing.JFrame;
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kirubaharan
 */
public class Add_teacher extends javax.swing.JFrame {

    /**
     * Creates new form Add_teacher
     */
    public Add_teacher() {
        initComponents();
    }
     void clear()
  {
      t_id.setText("");
      t_name.setText("");
      t_age.setText("");
      t_mail.setText("");
      t_pass.setText("");
      t_sub.setText("");
      t_deg.setText("");
      tc_time.setText("");
      tc_id.setText( "");
      
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tcourse_time = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        t_age = new javax.swing.JTextField();
        t_mail = new javax.swing.JTextField();
        tc_time = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t_pass = new javax.swing.JTextField();
        t_sub = new javax.swing.JTextField();
        t_deg = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tc_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel2.setText("Teacher_Name ------------->");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, 30));

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel3.setText("Teacher_Exp---------------->");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, 30));

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel4.setText("Email_Id ---------------->");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, 30));

        tcourse_time.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        tcourse_time.setText("Course_time ------------->");
        jPanel2.add(tcourse_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, -1, 30));

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel6.setText("Teacher_Id ---------------->");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 30));

        t_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });
        jPanel2.add(t_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 74, 250, 50));

        t_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });
        jPanel2.add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 250, 50));

        t_age.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        t_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ageActionPerformed(evt);
            }
        });
        jPanel2.add(t_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 250, 50));

        t_mail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        t_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_mailActionPerformed(evt);
            }
        });
        jPanel2.add(t_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 250, 50));

        tc_time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        tc_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tc_timeActionPerformed(evt);
            }
        });
        jPanel2.add(tc_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 550, 250, 50));

        jLabel7.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel7.setText("Password ---------------->");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, -1, 30));

        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel8.setText("Subject ------------------>");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, -1, 30));

        jLabel9.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel9.setText("Degree ------------------>");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, -1, 30));

        t_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        t_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passActionPerformed(evt);
            }
        });
        jPanel2.add(t_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 70, 250, 50));

        t_sub.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        t_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_subActionPerformed(evt);
            }
        });
        jPanel2.add(t_sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 180, 250, 50));

        t_deg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        t_deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_degActionPerformed(evt);
            }
        });
        jPanel2.add(t_deg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 300, 250, 50));

        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jToggleButton3.setText("Submit");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jToggleButton4.setText("clear");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 110, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\search.png")); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 110, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 110, 40));

        jLabel10.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel10.setText("Course_Id ------------->");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, -1, 30));

        tc_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        tc_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tc_idActionPerformed(evt);
            }
        });
        jPanel2.add(tc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 430, 250, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\grey.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 760, 290, 110));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\grey.png")); // NOI18N
        jLabel11.setText("jLabel5");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1360, 800));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\grey.png")); // NOI18N
        jLabel12.setText("jLabel5");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, -20, 290, 800));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\grey.png")); // NOI18N
        jLabel13.setText("jLabel5");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 290, 110));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\grey.png")); // NOI18N
        jLabel14.setText("jLabel5");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 760, 290, 110));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\grey.png")); // NOI18N
        jLabel15.setText("jLabel5");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 760, 290, 110));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\grey.png")); // NOI18N
        jLabel16.setText("jLabel5");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 760, 290, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1550, 860));

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher Entry");

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setText("EXIT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(726, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334)
                .addComponent(jToggleButton1)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jToggleButton1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameActionPerformed

    private void t_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ageActionPerformed

    private void t_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_mailActionPerformed

    private void tc_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tc_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tc_timeActionPerformed

    private void t_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passActionPerformed

    private void t_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_subActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subActionPerformed

    private void t_degActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_degActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_degActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
       String t1_id1 = t_id.getText();
    String t1_name = t_name.getText();
    String t1_age = t_age.getText();
    String t1_mail = t_mail.getText();
    String t1_pass = t_pass.getText();
    String t1_sub = t_sub.getText();
    String t1_deg = t_deg.getText();
    String tc1_id = tc_id.getText();
    String tc1_time = tc_time.getText();

    // Validate form fields
    if (t1_id1.isEmpty() || t1_name.isEmpty() || t1_age.isEmpty() || t1_mail.isEmpty() || 
        t1_pass.isEmpty() || t1_sub.isEmpty() || t1_deg.isEmpty() || tc1_id.isEmpty() || tc1_time.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields must be filled out.");
        return;
    }

    // Validate age as a numeric value
    try {
        int exp = Integer.parseInt(t1_age);
        if (exp <= 0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid age.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Age must be a number.");
        return;
    }

    // Validate email format
    if (!t1_mail.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
        JOptionPane.showMessageDialog(null, "Please enter a valid email address.");
        return;
    }

    // Validate class time format (e.g., HH:mm)
    

    // Proceed to save data if all validations pass
    try {
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();
        st.executeUpdate("INSERT INTO teacher VALUES('" + t1_id1 + "', '" + t1_name + "', '" + t1_age + "', '" +
                          t1_mail + "', '" + t1_pass + "', '" + t1_sub + "', '" + t1_deg + "', '" + tc1_id + "', '" + tc1_time + "')");

        JOptionPane.showMessageDialog(null, "Successfully Updated");
        clear();  // Clear form fields after successful entry
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
               admin_mgmt am =new admin_mgmt();
               am.setExtendedState(JFrame.MAXIMIZED_BOTH);
               am.setVisible(true); 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id1=t_id.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from teacher where t_id='"+id1+"'");
            if(rs.next())
            {
                t_id.setText(rs.getString(1));
                t_name.setText(rs.getString(2));
                t_age.setText(rs.getString(3));
                t_mail.setText(rs.getString(4));
                t_pass.setText(rs.getString(5));
                t_sub.setText(rs.getString(6));
                t_deg.setText(rs.getString(7));
                tc_time.setText(rs.getString(8));
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Product doesn't Exits");
                clear();
            }}
            catch(Exception e)
            {

            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 String t1_id1 = t_id.getText();
String t1_name = t_name.getText();
String t1_age = t_age.getText();
String t1_mail = t_mail.getText();
String t1_pass = t_pass.getText();
String t1_sub = t_sub.getText();
String t1_deg = t_deg.getText();
String tc1_id = tc_id.getText();
String tc1_time = tc_time.getText();

try
{
    Connection con = ConnectionProvider.getCon();
    Statement st = con.createStatement();

    // Build the SQL query string to update an existing teacher record
    String query = "UPDATE teacher SET t_name='" + t1_name + "', t_age='" + t1_age + "', t_email='" + t1_mail + "'," +
                   " t_password='" + t1_pass + "', t_sub='" + t1_sub + "', t_qual='" + t1_deg + "', course_id='" + tc1_id + "',course_time='" + tc1_time + "'" +
                   " WHERE t_id='" + t1_id1 + "'";

    // Execute the SQL query
    int result = st.executeUpdate(query);
    
    if (result > 0) {
        clear(); 
        JOptionPane.showMessageDialog(null, "Successfully Updated");
    } else {
        JOptionPane.showMessageDialog(null, "No record found with the provided ID");
    }
}
catch(Exception e)
{
    // Display the actual error message from the exception
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String tId=t_id.getText();
        int a=JOptionPane.showConfirmDialog(null,"Do you want to delete?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                st.executeUpdate("delete from teacher where t_id='"+tId+"'");
                JOptionPane.showMessageDialog(null,"Successfully Deleted");
                clear();
            }
            catch(Exception e)
            {}
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tc_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tc_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tc_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Add_teacher at =new Add_teacher();
               at.setExtendedState(JFrame.MAXIMIZED_BOTH);
               at.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextField t_age;
    private javax.swing.JTextField t_deg;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_mail;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_pass;
    private javax.swing.JTextField t_sub;
    private javax.swing.JTextField tc_id;
    private javax.swing.JTextField tc_time;
    private javax.swing.JLabel tcourse_time;
    // End of variables declaration//GEN-END:variables
}
