
import javax.swing.JFrame;
import Project.ConnectionProvider;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.print.attribute.standard.Media;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kirubaharan
 */
public class classroom extends javax.swing.JFrame {

    /**
     * Creates new form classroom
     */
    public classroom(String Stud_id) {
        initComponents();
        String s1_id=Stud_id;
        sid.setText(s1_id);
    }

    private classroom() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        videosTable = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        cour_id = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        sid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        videosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "videoTitle", "videoUrl"
            }
        ));
        videosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(videosTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 630, 540));

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setText("EXIT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course_id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        cour_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(cour_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 120, 30));

        jToggleButton2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jToggleButton2.setText("Click");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 90, -1));

        jToggleButton3.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jToggleButton3.setText("Attend Test");
        jToggleButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 3));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 220, 40));
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\dark1.png")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 930));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
               stud_display sd1 =new stud_display();
               sd1.setExtendedState(JFrame.MAXIMIZED_BOTH);
               sd1.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

        // TODO add your handling code here:
         loadVideosForCourse();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void videosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videosTableMouseClicked
        // TODO add your handling code here:
        int row = videosTable.getSelectedRow(); // Get the selected row index
        if (row != -1) { // Check if a row is selected
            String videoUrl = (String) videosTable.getValueAt(row, 1); // Get the video URL from the second column
            playVideo(videoUrl); // Call the playVideo method with the selected video URL
        }
    }//GEN-LAST:event_videosTableMouseClicked

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        String Student_id=sid.getText();
        String Course_id =cour_id.getText();
        
        quiz qz = new quiz(Student_id,Course_id);
                qz.setExtendedState(JFrame.MAXIMIZED_BOTH);
                qz.setVisible(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void loadVideosForCourse() {
    
        DefaultTableModel model = (DefaultTableModel) videosTable.getModel(); // Assuming you have a JTable named videosTable
    
        model.setRowCount(0); // Clear existing rows
        String courseId = cour_id.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            String sql = "SELECT video_title, video_url FROM Videos WHERE course_id = ?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1, courseId);
            ResultSet rs = pstmt.executeQuery();
        
                while (rs.next()) 
                {
                    String videoTitle = rs.getString("video_title");
                    String videoUrl = rs.getString("video_url");
                    model.addRow(new Object[]{videoTitle, videoUrl}); // Add each video to the table
                }
            } 
        catch (SQLException e) 
        {
                   JOptionPane.showMessageDialog(null, "Error loading videos: " + e.getMessage());
        }
}
     private void playVideo(String videoUrl) {
        try {
            // Command to run VLC media player and play the video
            String command = "\"C:\\Program Files\\VideoLAN\\VLC\\vlc.exe\" \"" + videoUrl + "\"";


            // Execute the command
            Runtime.getRuntime().exec(command);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error playing video: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(classroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(classroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(classroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(classroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                classroom cr = new classroom();
                cr.setExtendedState(JFrame.MAXIMIZED_BOTH);
                cr.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cour_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField sid;
    private javax.swing.JTable videosTable;
    // End of variables declaration//GEN-END:variables
}
