
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kirubaharan
 */
public class create_quiz extends javax.swing.JFrame {

    /**
     * Creates new form create_quiz
     */
    public create_quiz(String teacherSubject, String teacherId) {
        initComponents();
         t1_id.setText(teacherId);
        ts1.setText(teacherSubject);
        t1_id.setEditable(false);
        ts1.setEditable(false);
        
    }

    create_quiz() {
        
       
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ts1 = new javax.swing.JTextField();
        t1_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        op4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ques = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        op1 = new javax.swing.JTextField();
        op2 = new javax.swing.JTextField();
        op3 = new javax.swing.JTextField();
        res = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        stnd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 20)); // NOI18N
        jLabel4.setText("Subject");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        dte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dteActionPerformed(evt);
            }
        });
        jPanel1.add(dte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 120, 30));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 70, -1));
        jPanel1.add(ts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 120, 30));
        jPanel1.add(t1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Enter Question");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Correct Answer");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Option:1");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Option:2");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Option:3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        op4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.add(op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 240, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Option:4");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\teach.png")); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 630, 560));

        ques.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 649, 53));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setText("Teacher_Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        op1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 235, -1));

        op2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 240, -1));

        op3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 240, -1));

        res.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 240, -1));

        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\add.png")); // NOI18N
        jToggleButton1.setText("Upload");
        jToggleButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 111, 40));

        jLabel13.setFont(new java.awt.Font("Pristina", 1, 20)); // NOI18N
        jLabel13.setText("Standard");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 80, 30));
        jPanel1.add(stnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 120, 30));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\Close all jframe.png")); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 30, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\lr1.png")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 810));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 800));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teacher_Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teacher_Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        
        String Ques = ques.getText();
        String opt1 = op1.getText();
        String opt2 = op2.getText();
        String opt3 = op3.getText();
        String opt4 = op4.getText();
        String ans = res.getText();
        String t2_id= t1_id.getText();
        String ts2= ts1.getText();
        String d1=dte.getText();
        int ans1=Integer.parseInt(ans);
        String stand=stnd.getText();
        
        saveQuizToDatabase(Ques, stand,opt1, opt2, opt3, opt4, ans1, ts2, t2_id,d1);
                                                  
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void dteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         teach_display td =new teach_display();
               td.setExtendedState(JFrame.MAXIMIZED_BOTH);
               td.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
        
    
    
     private void saveQuizToDatabase(String question,String stand ,String option1, String option2, String option3, String option4, Integer answer, String courseId, String teacherId, String d1) {
    try {
        // Establish database connection
        Connection con = ConnectionProvider.getCon();
        String sql = "INSERT INTO Questions (course_id, t_id,standard,question_text, option_a, option_b, option_c, option_d, correct_option, q_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pstmt = con.prepareStatement(sql);

        // Parse the date from the string
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate quizDate = LocalDate.parse(d1, formatter);  // Assuming the date is in "yyyy-MM-dd" format
        java.sql.Date sqlDate = java.sql.Date.valueOf(quizDate);  // Convert to SQL date
        
        // Set parameters for the SQL query
        pstmt.setString(1, courseId);  // Set course_id
        pstmt.setString(2, teacherId); 
        pstmt.setString(3, stand);
        pstmt.setString(4, question);  // Set question text
        pstmt.setString(5, option1);   // Set option_a
        pstmt.setString(6, option2);   // Set option_b
        pstmt.setString(7, option3);   // Set option_c
        pstmt.setString(8, option4);   // Set option_d
        pstmt.setInt(9, answer);       // Set correct_option
        pstmt.setDate(10, sqlDate);     // Set q_date
        
        // Execute the update
        int rowsAffected = pstmt.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Quiz created successfully!");
            // Optionally reset fields after saving
            ques.setText("");
            op1.setText("");
            op2.setText("");
            op3.setText("");
            op4.setText("");
            res.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to create quiz. Please try again.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error while creating quiz: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                create_quiz crqz = new create_quiz();
                crqz.setExtendedState(JFrame.MAXIMIZED_BOTH);
                crqz.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField op1;
    private javax.swing.JTextField op2;
    private javax.swing.JTextField op3;
    private javax.swing.JTextField op4;
    private javax.swing.JTextField ques;
    private javax.swing.JTextField res;
    private javax.swing.JTextField stnd;
    private javax.swing.JTextField t1_id;
    private javax.swing.JTextField ts1;
    // End of variables declaration//GEN-END:variables
}
