
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kirubaharan
 */
public class Parent_display extends javax.swing.JFrame {

    /**
     * Creates new form Parent_display
     */
    public Parent_display(String StudentId) {
        initComponents();
        sd_id.setText(StudentId);
       
    }

    Parent_display() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sd_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sd_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sd_std = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel6.setText("Student_Id ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 127, 30));

        sd_id.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        sd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_idActionPerformed(evt);
            }
        });
        jPanel1.add(sd_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 250, 50));

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel5.setText("Student_Name ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        sd_name.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        sd_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_nameActionPerformed(evt);
            }
        });
        jPanel1.add(sd_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 250, 50));

        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel8.setText("Standard ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 139, 30));

        sd_std.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        sd_std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_stdActionPerformed(evt);
            }
        });
        jPanel1.add(sd_std, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 250, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course_Id", "Course_Name", "Mark", "Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 470, 450));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, -1, 440));

        jToggleButton2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jToggleButton2.setText("View Scores");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 310, -1));

        jToggleButton3.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jToggleButton3.setText("View Attendance");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jButton1.setText("display");
        jButton1.setActionCommand("Display");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 100, -1));

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\Close all jframe.png")); // NOI18N
        jToggleButton1.setText("EXIT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\lr1.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_idActionPerformed

    private void sd_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_nameActionPerformed

    private void sd_stdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_stdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_stdActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        String studentId = sd_id.getText();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        try {
            Connection con = ConnectionProvider.getCon(); // Ensure you have a method to get the database connection

            String sql = "SELECT c.course_id, c.course_name, qa.marks, qa.attempt_date " +
            "FROM courses c " +
            "JOIN enrollments e ON c.course_id = e.course_id " +
            "JOIN quiz_attempts qa ON e.course_id = qa.course_id AND e.st_id = qa.student_id " +
            "WHERE e.st_id = ?";

            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1, studentId);  // Set the student ID in the query
            ResultSet rs = pstmt.executeQuery();

            // Clear previous data in the table model
            model.setRowCount(0);

            // Loop through the result set and populate the table model
            while (rs.next()) {
                String courseId = rs.getString("course_id");
                String courseName = rs.getString("course_name");
                int marks = rs.getInt("marks");
                java.sql.Date date = rs.getDate("attempt_date");

                // Add a new row to the table model
                model.addRow(new Object[]{courseId, courseName, marks, date});
            }

            // Close resources
            rs.close();
            pstmt.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading course data: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:String studentId = stud_id.getText(); // Get student ID
        String studentId = sd_id.getText(); // Get student ID
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear previous rows

        try {
            // Database connection
            Connection con = ConnectionProvider.getCon();

            // Query to fetch attendance for the student
            String sql = "SELECT c.course_name, a.attendance_date, a.status "
            + "FROM Attendance a JOIN Courses c ON a.course_id = c.course_id "
            + "WHERE a.st_id = ? ORDER BY a.attendance_date";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1, studentId);
            ResultSet rs = pstmt.executeQuery();

            // Populate the table with attendance data
            while (rs.next()) {
                String courseName = rs.getString("course_name");
                String date = rs.getString("attendance_date");
                String status = rs.getString("status");

                // Add row to table
                model.addRow(new Object[]{courseName, date, status});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error fetching attendance: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s_id = sd_id.getText();
        try {
        // Establish database connection
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();

        // SQL query to check user credentials
        String sql = "SELECT * FROM student WHERE st_id = '" + s_id + "'";
        ResultSet rs = st.executeQuery(sql);

        // Check if the user exists
        if (rs.next()) {
            // Retrieve student details from the ResultSet
            
            String studentName = rs.getString("name");
            String studentStd = rs.getString("stnd");
            sd_name.setText(studentName);
            sd_std.setText(studentStd);
           
        }
        } 
        catch (SQLException e) {
        // SQL-related exceptions
        JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
        e.printStackTrace();
    } catch (Exception e) {
        // Catch any other general exceptions
        JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + e.getMessage());
        e.printStackTrace();
    }    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
         par_log pl8 =new par_log();
               pl8.setExtendedState(JFrame.MAXIMIZED_BOTH);
               pl8.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parent_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parent_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parent_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parent_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Parent_display pd = new Parent_display();
                pd.setExtendedState(JFrame.MAXIMIZED_BOTH);
                pd.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField sd_id;
    private javax.swing.JTextField sd_name;
    private javax.swing.JTextField sd_std;
    // End of variables declaration//GEN-END:variables
}
