
import javax.swing.JFrame;
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kirubaharan
 */
public class stud_display extends javax.swing.JFrame {

    /**
     * Creates new form stud_display
     */
    public stud_display(String studentId, String studentName, String studentAge, String studentStd, String studentMail) {
        initComponents(); // Initialize components (should be auto-generated)
        
        // Set student information to the respective labels
        sd_id.setText( studentId);
        sd_name.setText( studentName);
        sd_age.setText( studentAge);
        sd_std.setText( studentStd);
        sd_mail.setText( studentMail);
    }

    public stud_display() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sd_name = new javax.swing.JTextField();
        sd_age = new javax.swing.JTextField();
        sd_std = new javax.swing.JTextField();
        sd_mail = new javax.swing.JTextField();
        sd_id = new javax.swing.JTextField();
        jToggleButton5 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 203, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel4.setText("Student Details :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 206, 28));

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel6.setText("Student_Id ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 127, 30));

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel5.setText("Student_Name ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jLabel7.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel7.setText("Student_Age ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 157, 30));

        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel8.setText("Standard ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 139, 30));

        jLabel9.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel9.setText("Mail ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 118, 30));

        sd_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_nameActionPerformed(evt);
            }
        });
        jPanel1.add(sd_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 250, 50));

        sd_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_ageActionPerformed(evt);
            }
        });
        jPanel1.add(sd_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 250, 50));

        sd_std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_stdActionPerformed(evt);
            }
        });
        jPanel1.add(sd_std, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 250, 50));

        sd_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_mailActionPerformed(evt);
            }
        });
        jPanel1.add(sd_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 250, 50));

        sd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sd_idActionPerformed(evt);
            }
        });
        jPanel1.add(sd_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 250, 50));

        jToggleButton5.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jToggleButton5.setText("Classroom");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 159, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course_Id", "Course_Name", "Mark", "Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 470, 450));

        jToggleButton2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jToggleButton2.setText("View Scores");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 310, 50));

        jLabel10.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel10.setText("Student_Name ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 1060, 760));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamil", "English", "Maths", "Science", "Social" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jToggleButton3.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jToggleButton3.setText("View Attendance");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jToggleButton4.setText("Enroll Course");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton3)
                .addGap(110, 110, 110))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jToggleButton3)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jToggleButton4)
                    .addContainerGap(813, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 880));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setText("Scoodemy");

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kirubaharan\\Documents\\NetBeansProjects\\learning_platform\\src\\img1\\Close all jframe.png")); // NOI18N
        jToggleButton1.setText("EXIT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 1060, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        student_login sl =new student_login();
               sl.setExtendedState(JFrame.MAXIMIZED_BOTH);
               sl.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:String studentId = stud_id.getText(); // Get student ID
        String studentId = sd_id.getText(); // Get student ID
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear previous rows

    try {
        // Database connection
        Connection con = ConnectionProvider.getCon();

        // Query to fetch attendance for the student
        String sql = "SELECT c.course_name, a.attendance_date, a.status "
                   + "FROM Attendance a JOIN Courses c ON a.course_id = c.course_id "
                   + "WHERE a.st_id = ? ORDER BY a.attendance_date";
        PreparedStatement pstmt = con.prepareStatement(sql);
        pstmt.setString(1, studentId);
        ResultSet rs = pstmt.executeQuery();

        // Populate the table with attendance data
        while (rs.next()) {
            String courseName = rs.getString("course_name");
            String date = rs.getString("attendance_date");
            String status = rs.getString("status");

            // Add row to table
            model.addRow(new Object[]{courseName, date, status});
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error fetching attendance: " + e.getMessage());
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        String studentId = sd_id.getText(); 
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

    try {
        Connection con = ConnectionProvider.getCon(); // Ensure you have a method to get the database connection
        
       String sql = "SELECT c.course_id, c.course_name, qa.marks, qa.attempt_date " +
             "FROM courses c " +
             "JOIN enrollments e ON c.course_id = e.course_id " +
             "JOIN quiz_attempts qa ON e.course_id = qa.course_id AND e.st_id = qa.student_id " + 
             "WHERE e.st_id = ?";

                     
        PreparedStatement pstmt = con.prepareStatement(sql);
        pstmt.setString(1, studentId);  // Set the student ID in the query
        ResultSet rs = pstmt.executeQuery();

        // Clear previous data in the table model
        model.setRowCount(0);

        // Loop through the result set and populate the table model
        while (rs.next()) {
            String courseId = rs.getString("course_id");
            String courseName = rs.getString("course_name");
            int marks = rs.getInt("marks");
            java.sql.Date date = rs.getDate("attempt_date");

            // Add a new row to the table model
            model.addRow(new Object[]{courseId, courseName, marks, date});
        }

        // Close resources
        rs.close();
        pstmt.close();
        con.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading course data: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void sd_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_nameActionPerformed

    private void sd_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_ageActionPerformed

    private void sd_stdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_stdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_stdActionPerformed

    private void sd_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_mailActionPerformed

    private void sd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sd_idActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        String Stud_id=sd_id.getText();
        classroom cr = new classroom(Stud_id);
                cr.setExtendedState(JFrame.MAXIMIZED_BOTH);
                cr.setVisible(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedCourse = jComboBox1.getSelectedItem().toString();
    String studentId = sd_id.getText(); // Assuming you have this from the login process

    try {
        // Database connection
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();

        // Find course ID based on selected course name
        String sql = "SELECT course_id FROM Courses WHERE course_name = ?";
        PreparedStatement courseStmt = con.prepareStatement(sql);
        courseStmt.setString(1, selectedCourse);
        ResultSet rs = courseStmt.executeQuery();

        if (rs.next()) {
            String courseId = rs.getString("course_id"); // Assuming course_id is VARCHAR or STRING

            // Check if the student is already enrolled in this course
            String checkEnrollmentSql = "SELECT * FROM Enrollments WHERE st_id = ? AND course_id = ?";
            PreparedStatement checkStmt = con.prepareStatement(checkEnrollmentSql);
            checkStmt.setString(1, studentId);
            checkStmt.setString(2, courseId);
            ResultSet checkRs = checkStmt.executeQuery();

            if (checkRs.next()) {
                // Student is already enrolled in this course
                JOptionPane.showMessageDialog(null, "You are already enrolled in " + selectedCourse);
            } else {
                // Enroll student in the course
                String enrollSql = "INSERT INTO Enrollments (st_id, course_id) VALUES (?, ?)";
                PreparedStatement pstmt = con.prepareStatement(enrollSql);
                pstmt.setString(1, studentId); // Assuming student ID is stored as VARCHAR in the DB
                pstmt.setString(2, courseId);

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "You have successfully enrolled in " + selectedCourse);
            }

            checkRs.close();
            checkStmt.close();
        } else {
            JOptionPane.showMessageDialog(null, "Course not found.");
        }

        rs.close();
        courseStmt.close();
        st.close();
        con.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error enrolling in course: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stud_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stud_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stud_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stud_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               stud_display sd1 =new stud_display();
               sd1.setExtendedState(JFrame.MAXIMIZED_BOTH);
               sd1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JTextField sd_age;
    private javax.swing.JTextField sd_id;
    private javax.swing.JTextField sd_mail;
    private javax.swing.JTextField sd_name;
    private javax.swing.JTextField sd_std;
    // End of variables declaration//GEN-END:variables
}
